### ISSUE TITLE
3.0 Todo

### ISSUE THREAD

**Issue by AshesOfOwls** [AshesOfOwls/jquery.shapeshift#58]
- [x] CSS3 Transitions #23 
- [x] Percentage gutter #50
- [x] Auto Gutter #45 
- [x] Figure out what to do when a colspan is larger than the column count #30 
- [x] Better initial options for containers initialized with no elements #47 
- [ ] Dragging algorithm which better supports ie8 #19 
- [ ] 'Replacing' dragging algorithm #27 
- [ ] Fix / optimize cloning #57
- [ ] Undo / history functions
- [ ] Better Padding #41 
- [ ] Row vs Column algorithms #49 
- [ ] Better initialization of elements with dragging considered #43 #34 
- [ ] IE8 hates .map. Don't use it. #60 
- [ ] iframe as an element #54 
- [ ] Documentation for handles #55
- [ ] Cursor Placement #67 

If I get the time:
- [ ] Hover states for touch devices. #62

**Comment by jackmarketon** [comment]
What are you planning for autogutter/better padding? I could assist with this.

Also as a suggustion for #30, I'd just force the element to max-width container element so colspan == column count.

**Comment by AshesOfOwls** [comment]
That's actually the step I have been currently working on but definitely am having some issues with. I am going to make some progress today and push up to the branch and I'll let you know when I do that, I would love any assistance.

As for #30 if I understand you correctly then the elements would change width if it was larger than the container. I am trying to stay away from changing the actual width of elements because the plugin is already a little laggy when dealing with a lot of items and I feel like having to continuously check for large elements and then setting their width is adding a lot of complexity. It also requires that all elements are designed to be responsive which may not be appropriate for certain situations. 

I took a look at what the other layout plugins are doing such as Isotope and it seems they just keep the element the same width but have overflow: hidden on the parent container to prevent any weird clipping.

Maybe there is a possibility to have that functionality as the default behavior and then take your suggestion and enable it with an option for people looking for highly responsive designs.

**Comment by jackmarketon** [comment]
Let me know, I think looking towards responsive style setup would make autogutter/padding better.

#30, understandable, but damn I do hate overflow hidden...

**Comment by AshesOfOwls** [comment]
Yeah overflow sucks. Re-reading your comment I'm wondering if I didn't get it at first. It would definitely be plausible to set the max-width of the container to match the largest span item which would then force a horizontal scroll bar but that might be better off than overflow.

**Comment by jackmarketon** [comment]
Oh no, I meant set the max-width of the span element to 100% (or width to 100%), although it requires responsive implementation to work well...

**Comment by AshesOfOwls** [comment]
Ok I pushed up the changes to 3.0. The coding is a bit iffy but there are a lot of different situations to handle with this. Let me know if you have any ideas or suggestions!

**Comment by bazzooka** [comment]
I tried to make it compatible with IE8 the only thing to do is to add a polyfill for Array.map.
I recommand to you to use this polyfill : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Polyfill

You'll have a little things to do on CSS but it's easy.
For me the drag and drop is not enought performant :(

**Comment by RobbeR** [comment]
Any solution of #67 ? Thanks in advance

**Comment by pedrocruz27** [comment]
Has someone found a solution for #67?
